/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/listings/$id': typeof ListingsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/listings/$id': typeof ListingsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/listings/$id': typeof ListingsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/sitemap.xml'
    | '/listings/$id'
    | '/messages/$id'
    | '/requests/$id'
    | '/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/sitemap.xml'
    | '/listings/$id'
    | '/messages/$id'
    | '/requests/$id'
    | '/u/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/sitemap.xml'
    | '/listings/$id'
    | '/messages/$id'
    | '/requests/$id'
    | '/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ListingsIdRoute: typeof ListingsIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  UIdRoute: typeof UIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ListingsIdRoute: ListingsIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  UIdRoute: UIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
